name = "homogenous_SIR_model"
uuid = "65436762-333d-4b50-a69c-bc1e679150c6"
authors = ["Hamish Hunter <u7498619@anu.edu.au> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
