name = "homogenous_SIR_model"
uuid = "65436762-333d-4b50-a69c-bc1e679150c6"
authors = ["Hamish Hunter <u7498619@anu.edu.au> and contributors"]
version = "1.0.0-DEV"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
